Presentation/Energy.Web/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Energy.Web.Extensions;
using Energy.Web.Models.Directory;
using Energy.Core;
using Energy.Core.Domain.Directory;
using Energy.Services.Common;
using Energy.Services.Directory;
using Energy.Services.ExportImport;
using Energy.Services.Localization;
using Energy.Services.Security;
using Energy.Services.Stores;
using Energy.Web.Framework.Controllers;
using Energy.Web.Framework.Kendoui;
using Energy.Web.Framework.Mvc;

namespace Energy.Web.Controllers
{
    public partial class RegionController : BaseAdminController
    {
        #region Fields

        private readonly IRegionService _regionService;
        private readonly IDistributionAreaService _distributionAreaService;
        private readonly IPermissionService _permissionService;
        private readonly IExportManager _exportManager;

        #endregion

        #region Constructors

        public RegionController(IRegionService regionService,
            IDistributionAreaService distributionAreaService,
            IPermissionService permissionService,
            IExportManager exportManager)
        {
            this._regionService = regionService;
            this._distributionAreaService = distributionAreaService;
            this._permissionService = permissionService;
            this._exportManager = exportManager;
        }

        #endregion

        #region Regions

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public ActionResult RegionList(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var regions = _regionService.GetAllRegions(true);
            var gridModel = new DataSourceResult
            {
                Data = regions.Select(x => x.ToModel()),
                Total = regions.Count
            };

            return Json(gridModel);
        }

        public ActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var model = new RegionModel();
            //default values
            model.Published = true;
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public ActionResult Create(RegionModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var region = model.ToEntity();
                _regionService.InsertRegion(region);

                SuccessNotification("Admin.Configuration.Regions.Added");
                return continueEditing ? RedirectToAction("Edit", new { id = region.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var region = _regionService.GetRegionById(id);
            if (region == null)
                //No Region found with the specified id
                return RedirectToAction("List");

            var model = region.ToModel();

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public ActionResult Edit(RegionModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var region = _regionService.GetRegionById(model.Id);
            if (region == null)
                //No Region found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                region = model.ToEntity(region);
                _regionService.UpdateRegion(region);

                SuccessNotification("Admin.Configuration.Regions.Updated");

                if (continueEditing)
                {
                    //selected tab
                    SaveSelectedTabIndex();

                    return RedirectToAction("Edit", new { id = region.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var region = _regionService.GetRegionById(id);
            if (region == null)
                //No Region found with the specified id
                return RedirectToAction("List");

            try
            {
                _regionService.DeleteRegion(region);

                SuccessNotification("Admin.Configuration.Countries.Deleted");
                return RedirectToAction("List");
            }
            catch (Exception exc)
            {
                ErrorNotification(exc);
                return RedirectToAction("Edit", new { id = region.Id });
            }
        }

        [HttpPost]
        public ActionResult PublishSelected(ICollection<int> selectedIds)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            if (selectedIds != null)
            {
                var regions = _regionService.GetRegionsByIds(selectedIds.ToArray());
                foreach (var region in regions)
                {
                    region.Published = true;
                    _regionService.UpdateRegion(region);
                }
            }

            return Json(new { Result = true });
        }
        [HttpPost]
        public ActionResult UnpublishSelected(ICollection<int> selectedIds)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            if (selectedIds != null)
            {
                var regions = _regionService.GetRegionsByIds(selectedIds.ToArray());
                foreach (var region in regions)
                {
                    region.Published = false;
                    _regionService.UpdateRegion(region);
                }
            }
            return Json(new { Result = true });
        }

        #endregion

        #region Distribution Area

        [HttpPost]
        public ActionResult DistributionAreas(int RegionId, DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var das = _distributionAreaService.GetDistributionAreasByRegionId(RegionId, true);

            var gridModel = new DataSourceResult
            {
                Data = das.Select(x => x.ToModel()),
                Total = das.Count
            };
            return Json(gridModel);
        }

        //create
        public ActionResult DistributionAreaCreatePopup(int RegionId)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var model = new DistributionAreaModel();
            model.RegionId = RegionId;
            //default value
            model.Published = true;
            return View(model);
        }

        [HttpPost]
        public ActionResult DistributionAreaCreatePopup(string btnId, string formId, DistributionAreaModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var Region = _regionService.GetRegionById(model.RegionId);
            if (Region == null)
                //No Region found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                var sp = model.ToEntity();

                _distributionAreaService.InsertDistributionArea(sp);

                ViewBag.RefreshPage = true;
                ViewBag.btnId = btnId;
                ViewBag.formId = formId;
                return View(model);
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        //edit
        public ActionResult DistributionAreaEditPopup(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var sp = _distributionAreaService.GetDistributionAreaById(id);
            if (sp == null)
                //No state found with the specified id
                return RedirectToAction("List");

            var model = sp.ToModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult DistributionAreaEditPopup(string btnId, string formId, DistributionAreaModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRegions))
                return AccessDeniedView();

            var sp = _distributionAreaService.GetDistributionAreaById(model.Id);
            if (sp == null)

Presentation/Energy.Web/Views/Region/Create.cshtml
@model RegionModel
@{
    //page title
    ViewBag.Title = T("افزودن منطقه توزیع جدید").Text;
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "country-form" }))
{
    @Html.AntiForgeryToken()
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Content/images/ico-configuration.png")" alt="" />
            @T("افزودن منطقه توزیع جدید") @Html.ActionLink("(" + T("بازگشت به فهرست منطقه های توزیع") + ")", "List")
        </div>
        <div class="options">
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

Presentation/Energy.Web/Views/Region/DistributionAreaCreatePopup.cshtml
@{
    Layout = "~/Views/Shared/_Root.Head.cshtml";
}
@model DistributionAreaModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Countries.States.AddNew").Text;
}
<div class="container" style="padding-top:20px;">
    <div class="page split-page">
        <div class="page-body">
            <div class="fieldset">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="section-header">
                        <div class="title">
                            <img src="@Url.Content("~/Content/images/ico-configuration.png")" alt="" />
                            افزودن اطلاعات برق منطقه ای
                        </div>
                        <div class="options">
                            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
                        </div>
                    </div>
                    @Html.Partial("_CreateOrUpdateDistributionArea", Model)
                }
            </div>
        </div>
    </div>
</div>

Presentation/Energy.Web/Views/Region/DistributionAreaEditPopup.cshtml
@{
    Layout = "~/Views/Shared/_Root.Head.cshtml";
}
@model DistributionAreaModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Countries.States.EditStateDetails").Text;
}
<div class="container" style="padding-top:20px;">
    <div class="page split-page">
        <div class="page-body">
            <div class="fieldset">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="section-header">
                        <div class="title">
                            <img src="@Url.Content("~/Content/images/ico-configuration.png")" alt="" />
                            ویرایش اطلاعات برق منطقه ای
                        </div>
                        <div class="options">
                            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
                        </div>
                    </div>
                    @Html.Partial("_CreateOrUpdateDistributionArea", Model)
                }
            </div>
        </div>
    </div>
</div>

Presentation/Energy.Web/Views/Region/Edit.cshtml
@model RegionModel
@{
    //page title
    ViewBag.Title = "ویرایش اطلاعات منطقه توزیع";
}
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "region-form" }))
{
    @Html.AntiForgeryToken()
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Content/images/ico-configuration.png")" alt="" />
            ویرایش اطلاعات منطقه توزیع - @Model.Name @Html.ActionLink("(بازگشت به لیست)", "List")
        </div>
        <div class="options">
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
            <span id="country-delete" class="k-button">@T("Admin.Common.Delete")</span>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
@Html.DeleteConfirmation("country-delete")

Presentation/Energy.Web/Views/Region/List.cshtml
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Regions").Text;
}
@Html.AntiForgeryToken()
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Content/images/ico-configuration.png")" alt="" />
        @T("فهرست منطقه های توزیع")
    </div>
    <div class="options">
        <a href="@Url.Action("Create")" class="k-button">@T("Admin.Common.AddNew")</a>
        <input type="button" id="publish-selected" class="k-button" value="@T("نمایش انتخاب شده ها")" />
        <input type="button" id="unpublish-selected" class="k-button" value="@T("عدم نمایش انتخاب شده ها")" />
        <a href="@Url.Action("ExportCsv")" class="k-button">@T("گزارش")</a>
    </div>
</div>
<table class="adminContent" style="width:100%">
    <tr>
        <td>
            <div id="regions-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#regions-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("RegionList", "Region"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        scrollable: false,
                        dataBound: onDataBound,
                        columns: [{
                            field: "Id",
                            headerTemplate: "<input id='mastercheckbox' type='checkbox'/>",
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: "<input type='checkbox' value='#=Id#' class='checkboxGroups'/>",
                            width: 50
                        }, {
                            field: "Name",
                            title: "@T("توزیع منطقه ای")",
                            width: 300
                        }, {
                            field: "NumberOfDistributionAreas",
                            title: "@T("برق منطقه ای")",
                            width: 100
                        }, {
                            field: "DisplayOrder",
                            title: "@T("ترتیب نمایش")",
                            width: 100
                        }, {
                            field: "Published",
                            title: "@T("نمایش")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Content/images/")active-#=Published#.gif" />'
                        }, {
                            field: "Id",
                            title: "@T("Admin.Common.Edit")",
                            width: 50,
                            template: '<a href="Edit/#=Id#">@T("Admin.Common.Edit")</a>'
                        }]
                    });
                });
            </script>
        </td>
    </tr>
</table>

<script type="text/javascript">
        var selectedIds = [];

        $(document).ready(function () {

            //"publish selected" button
            $('#publish-selected').click(function (e) {
                e.preventDefault();

                var postData = {
                    selectedIds: selectedIds
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache:false,
                    type: "POST",
                    url: "@(Url.Action("PublishSelected", "Country"))",
                    data: postData,
                    complete: function (data) {
                        //reload grid
                        var grid = $('#countries-grid').data('kendoGrid');
                        grid.dataSource.read();
                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        alert(thrownError);
                    },
                    traditional: true
                });
                return false;
            });
            
            //"unpublish selected" button
            $('#unpublish-selected').click(function (e) {
                e.preventDefault();

                var postData = {
                    selectedIds: selectedIds
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache:false,
                    type: "POST",
                    url: "@(Url.Action("UnpublishSelected", "Country"))",
                    data: postData,
                    complete: function (data) {
                        //reload grid
                        var grid = $('#countries-grid').data('kendoGrid');
                        grid.dataSource.read();
                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        alert(thrownError);
                    },
                    traditional: true
                });
                return false;
            });
            
            $('#mastercheckbox').click(function () {
                $('.checkboxGroups').attr('checked', $(this).is(':checked')).change();
            });

            //wire up checkboxes.
            $('#countries-grid').on('change', 'input[type=checkbox][id!=mastercheckbox]', function (e) {
                var $check = $(this);
                if ($check.is(":checked") == true) {
                    var checked = jQuery.inArray($check.val(), selectedIds);
                    if (checked == -1) {
                        //add id to selectedIds.
                        selectedIds.push($check.val());
                    }
                }
                else {
                    var checked = jQuery.inArray($check.val(), selectedIds);
                    if (checked > -1) {
                        //remove id from selectedIds.
                        selectedIds = $.grep(selectedIds, function (item, index) {
                            return item != $check.val();
                        });
                    }
                }
                updateMasterCheckbox();
            });
        });

    function onDataBound(e) {

        $('#countries-grid input[type=checkbox][id!=mastercheckbox]').each(function () {
            var currentId = $(this).val();
            var checked = jQuery.inArray(currentId, selectedIds);
            //set checked based on if current checkbox's value is in selectedIds.
            $(this).attr('checked', checked > -1);
        });

        updateMasterCheckbox();
    }

    function updateMasterCheckbox() {
        var numChkBoxes = $('#countries-grid input[type=checkbox][id!=mastercheckbox]').length;
        var numChkBoxesChecked = $('#countries-grid input[type=checkbox][id!=mastercheckbox]:checked').length;
        $('#mastercheckbox').attr('checked', numChkBoxes == numChkBoxesChecked && numChkBoxes > 0);
    }
</script>

@*import states form*@
<div id="importcsv-window" style="display:none;">
    @using (Html.BeginForm("ImportCsv", "Country", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <table style="text-align:left;">
            <tr>
                <td>
                    @T("Admin.Common.CsvFile"):
                </td>
                <td>
                    <input type="file" id="importcsvfile" name="importcsvfile" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" class="k-button" value="@T("Admin.Common.ImportFromCsv")" />
                </td>
            </tr>
        </table>
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#importcsv").click(function (e) {
            e.preventDefault();
            var window = $("#importcsv-window");
            if (!window.data("kendoWindow")) {
                window.kendoWindow({
                    modal: true,
                    width: "400px",
                    title: "@T("Admin.Common.ImportFromCsv")",
                    actions: ["Close"]
                });
            }
            window.data('kendoWindow').center().open();
        });
    });
</script>

Presentation/Energy.Web/Views/Region/_CreateOrUpdate.cshtml
@model RegionModel

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)

<div id="region-edit">
    <ul>
        <li @Html.RenderSelectedTabIndex(0, GetSelectedTabIndex())>
            @T("اطلاعات منطقه توزیع")
        </li>
        <li @Html.RenderSelectedTabIndex(1, GetSelectedTabIndex())>
            @T("فهرست برق منطقه ای")
        </li>
    </ul>
    <div>
        @TabInfo()
    </div>
    <div>
        @Tabdistributionarea()
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#region-edit").kendoTabStrip({
            animation: {
                open: {
                    effects: "fadeIn"
                }
            },
            select: tabstrip_on_tab_select
        });
    });
</script>

@{
    //custom tabs
    var eventMessage = new AdminTabStripCreated(this.Html, "region-edit");
    EngineContext.Current.Resolve<IEventPublisher>().Publish(eventMessage);
    foreach (var eventBlock in eventMessage.BlocksToRender)
    {
        @eventBlock
    }
}


@*save selected tab index*@
<input type="hidden" id="selected-tab-index" name="selected-tab-index" value="@(GetSelectedTabIndex())">

@helper TabInfo()
{
    <table class="adminContent customer-info-tab" style="width:100%">
        <tr>
            <td class="adminTitle" style="width:15%">
                @Html.LabelFor(model => model.Name):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.LabelFor(model => model.Published):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.Published)
                @Html.ValidationMessageFor(model => model.Published)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.LabelFor(model => model.DisplayOrder):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.DisplayOrder)
                @Html.ValidationMessageFor(model => model.DisplayOrder)
            </td>
        </tr>
    </table>
}
@helper Tabdistributionarea()
{
    if (Model.Id > 0)
    {
        <table class="adminContent">
            <tr>
                <td>
                    <div id="distributionarea-grid"></div>

                    <script>
                        $(document).ready(function () {
                            $("#distributionarea-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("DistributionAreas", "Region", new { regionId = Model.Id }))",
                                            type: "POST",
                                            dataType: "json",
                                            data: addAntiForgeryToken
                                        },
                                        destroy: {
                                            url: "@Html.Raw(Url.Action("DistributionAreaDelete", "Region"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: addAntiForgeryToken
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "Id"
                                        }
                                    },
                                    error: function (e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    numeric: false,
                                    previousNext: false,
                                    info: false
                                },
                                editable: {
                                    confirmation: false,
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [{
                                    field: "Name",
                                    title: "عنوان",
                                    width: 300
                                },  {
                                    field: "Published",
                                    title: "نمایش",
                                    width: 100,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '<img src="@Url.Content("~/Content/images/")active-#=Published#.gif" />'
                                }, {
                                    field: "DisplayOrder",
                                    title: "ترتیب نمایش",
                                    width: 100
                                }, {
                                    field: "Id",
                                    title: "@T("Admin.Common.Edit")",
                                    width: 100,
                                    template: "<input type='submit' value='@T("Admin.Common.Edit")' onclick=\"javascript:OpenWindow('@Url.Content("~/Region/DistributionAreaEditPopup/")#=Id#?btnId=btnRefresh&formId=region-form', 800, 450, true); return false;\" class='k-button' />"
                                }, {
                                    command: { name: "destroy", text: "@T("Admin.Common.Delete")" },
                                    title: "@T("Admin.Common.Delete")",
                                    width: 100
                                }]
                            });
                        });
                    </script>
                </td>
            </tr>
            <tr>
                <td width="100%">
                    <input type="submit" id="btnAddNewState" value="افزودن منطقه توزیع جدید" onclick="javascript:OpenWindow('@(Url.Action("DistributionAreaCreatePopup", "Region", new { regionId = Model.Id, btnId = "btnRefresh", formId = "region-form" }))', 800, 450, true); return false;" class="k-button" style="margin-top:10px"/>
                    <input type="submit" id="btnRefresh" style="display: none" />
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#btnRefresh').click(function () {
                                //refresh grid
                                var grid = $("#distributionarea-grid").data('kendoGrid');
                                grid.dataSource.read();

                                //return false to don't reload a page
                                return false;
                            });
                        });
                    </script>
                </td>
            </tr>
        </table>
    }
    else
    {
        <span>ابندا اطلاعات منطقه توزیع را وارد کرده و ذخیره نمایید</span>
    }
}