Presentation/Energy.Web/Models/Tariffs/TariffAreaModel.cs
using System;
using Energy.Web.Framework.Mvc;
using Energy.Core.Domain.Tariffs;

namespace Energy.Web.Models.Tariffs
{
    public class TariffAreaModel : BaseProEntityModel
    {
        public int TariffID { get; set; }
        public Tariff Tariff { get; set; }
        public Int32 FromDay { get; set; }
        public Int32 FromMonth { get; set; }
        public Int32 ToDay { get; set; }
        public Int32 ToMonth { get; set; }
        public Double Factor { get; set; }
        public String Title { get; set; }
        public String Description { get; set; }
    }
}

Presentation/Energy.Web/Models/Tariffs/TariffListModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Energy.Web.Framework;
using Energy.Web.Framework.Mvc;

namespace Energy.Web.Models.Tariffs
{
    public class TariffListModel : BaseProModel
    {
        public TariffListModel()
        {
            CTariffs = new List<SelectListItem>();
        }

        [ProResourceDisplayName("تعرفه")]
        public int CTariffId { get; set; }
        public IList<SelectListItem> CTariffs { get; set; }
    }
}

Presentation/Energy.Web/Models/Tariffs/TariffNormalModel.cs
using Energy.Web.Framework.Mvc;

namespace Energy.Web.Models.Tariffs
{
    public class TariffNormalModel : BaseProEntityModel
    {
    }
}

Presentation/Energy.Web/Controllers/TariffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Energy.Web.Models.Tariffs;
using Energy.Web.Extensions;
using Energy.Services.Security;
using Energy.Services.Tariffs;
using Energy.Web.Framework.Kendoui;
using Energy.Core.Domain.Constant;
using Energy.Web.Framework.Mvc;
using Energy.Core.Domain.Tariffs;

namespace Energy.Web.Controllers
{
    public class TariffController : BaseAdminController
    {
        #region Fields

        private readonly IPermissionService _permissionService;
        private readonly ITariffService _tariffService;

        #endregion

        #region Constructors

        public TariffController(IPermissionService permissionService,
            ITariffService tariffService)
        {
            this._permissionService = permissionService;
            this._tariffService = tariffService;
        }

        #endregion

        #region Utilities
        private string GetTariffName(int cTariff)
        {
            switch (cTariff)
            {
                case 1:
                    return "مصارف خانگی";
                case 2:
                    return "مصارف عمومی";
                case 3:
                    return "مصارف کشاورزی";
                case 4:
                    return "مصارف صنعتی";
                case 5:
                    return "سایر مصارف";
                default:
                    return "تعرفه ندارد";
            }
        }

        #endregion

        #region Methods

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult TariffAreaList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var model = new TariffListModel();
            model.CTariffs.Add(new SelectListItem { Text = "تمام تعرفه ها", Value = "0" });

            int i = 1;
            foreach (Enum enumValue in (typeof(CTariff)).GetEnumValues())
            {
                model.CTariffs.Add(new SelectListItem { Text = GetTariffName(i), Value = (i++).ToString() });
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult TariffAreaList(DataSourceRequest command, TariffListModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var tariffs = _tariffService.getAllTarrifArea(
                CTariff: model.CTariffId,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize);

            var gridModel = new DataSourceResult
            {
                Data = tariffs.Select(x =>
                {
                    var m = x.ToModel();
                    return m;
                }),
                Total = tariffs.TotalCount
            };

            return Json(gridModel);
        }

        [HttpPost]
        public ActionResult TariffAreaUpdate(TariffAreaModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var tariffArea = _tariffService.getTariffAreaById(model.Id);
            tariffArea = model.ToEntity(tariffArea);

            if (ModelState.IsValid)
            {
                _tariffService.UpdateTariffArea(tariffArea);
            }

            return new NullJsonResult();
        }

        ////////

        public ActionResult TariffList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var model = new TariffListModel();
            model.CTariffs.Add(new SelectListItem { Text = "تمام تعرفه ها", Value = "0" });

            int i = 1;
            foreach (Enum enumValue in (typeof(CTariff)).GetEnumValues())
            {
                model.CTariffs.Add(new SelectListItem { Text = GetTariffName(i), Value = (i++).ToString() });
            }
            return View("TariffList", model);
        }
        [HttpPost]
        public ActionResult TariffList(DataSourceRequest command, TariffListModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var tariffs = _tariffService.getAllTarrif(
                CTariff: model.CTariffId,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize);

            var gridModel = new DataSourceResult
            {
                Data = tariffs,
                Total = tariffs.TotalCount
            };

            return Json(gridModel);
        }

        [HttpPost]
        public ActionResult TariffUpdate(Tariff model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var tariff = _tariffService.GetById(model.Id);

            tariff.LimitCostKwh = model.LimitCostKwh;
            tariff.MaxFine = model.MaxFine;
            tariff.MinDiscount = model.MinDiscount;
            tariff.NoMaxDiscount = model.NoMaxDiscount;
            tariff.Factor = model.Factor;
            tariff.PowerCost = model.PowerCost;
            tariff.MidCost = model.MidCost;
            tariff.MaxCost = model.MaxCost;
            tariff.MinCost = model.MinCost;

            _tariffService.UpdateTariff(tariff);


            return new NullJsonResult();
        }

        ///

        public ActionResult TariffNormalList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var model = new TariffListModel();
            model.CTariffs.Add(new SelectListItem { Text = "تمام تعرفه ها", Value = "0" });

            int i = 1;
            foreach (Enum enumValue in (typeof(CTariff)).GetEnumValues())
            {
                if(i == 1 || i == 5)
                    model.CTariffs.Add(new SelectListItem { Text = GetTariffName(i), Value = (i).ToString() });
                i++;
            }
            return View("TariffNormalList", model);
        }
        [HttpPost]
        public ActionResult TariffNormalList(DataSourceRequest command, TariffListModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
                return AccessDeniedView();

            var tariffNormals = _tariffService.getAllTarrifNormal(
                CTariff: model.CTariffId,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize);

            var gridModel = new DataSourceResult
            {
                Data = tariffNormals,
                Total = tariffNormals.TotalCount
            };

            return Json(gridModel);
        }

        //[HttpPost]
        //public ActionResult TariffNormalUpdate(TariffRate model)
        //{
        //    if (!_permissionService.Authorize(StandardPermissionProvider.ManageTariffs))
        //        return AccessDeniedView();

        //    var tariff = _tariffService.GetById(model.Id);

        //    tariff.LimitCostKwh = model.FromKwhm;
        //    tariff.MaxFine = model.ToKwhm;
        //    tariff.MinDiscount = model.Cost;
        //    tariff.NoMaxDiscount = model.Title;
        //    tariff.Factor = model.Description;

        //    _tariffService.UpdateTariff(tariff);


        //    return new NullJsonResult();
        //}

        #endregion
    }
}

Presentation/Energy.Web/Views/Tariff/TariffAreaList.cshtml
@model TariffListModel
@using System.Globalization;
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Energy.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Energy.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = "لیست تعرفه ها";
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            @*<img src="@Url.Content("~/Content/images/ico-tariffs.png")" alt="" />*@
            <span class="page-title">لیست تعرفه مناطق</span>
        </div>
    </div>
    <div class="fieldset product-selectors">
        <table width="100%">
            <tr>
                <td class="adminTitle" style="width:10%">
                    @Html.LabelFor(model => model.CTariffId):
                </td>
                <td class="adminData">
                    @Html.DropDownList("CTariffId", Model.CTariffs)
                </td>
            </tr>
        </table>
    </div>
    <hr />
    <div class="fieldset">
        <table class="adminContent" style="width:100%;">
            <tr>
                <td>
                    <div class="k-rtl" id="tariffs-grid" style="width:100%;"></div>

                    <script>
                        $(document).ready(function () {
                            $("#tariffs-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("TariffAreaList", "Tariff"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: additionalData
                                        },
                                        update: {
                                            url:"@Html.Raw(Url.Action("TariffAreaUpdate", "Tariff"))",
                                            type: "POST",
                                            dataType: "json",
                                        },
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "Id", // define the model of the data source. Required for validation and property types.
                                            fields: {
                                                "Tariff.Title": { type: "string", editable: false }, //تعيين نوع فيلد براي جستجوي پويا مهم است
                                                "Title": { type: "string", editable: false },
                                                "Tariff.Description": { type: "string", editable: false },
                                                "Description": { type: "string", editable: false },
                                                "FromDay": { editable: true },
                                                "FromMonth": { editable: true },
                                                "ToDay": { editable: true },
                                                "ToMonth": { editable: true },
                                                "Factor":{ type: "string", editable: true,from:"Tariff.Factor" },
                                                "Test": {editable: true },
                                            }
                                        }
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(defaultGridPageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: false
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(gridPageSizes)]
                                },
                                sortable: true,
                                scrollable: false,
                                editable: {
                                    mode: "popup"
                                },
                                columns: [ {
                                    field: "Id",
                                    title: "شماره",
                                    width: 50
                                },{
                                    field: "Title",
                                    title: "عنوان",
                                    width: 100
                                },{
                                    field: "Tariff.Description",
                                    title: "توضیحات",
                                    width: 100,
                                },{
                                    field: "Description",
                                    title: "توضیحات",
                                    width: 350,
                                },{
                                    field: "Factor",
                                    title: "ضریب",
                                    width: 20,
                                },{
                                    field: "FromDay",
                                    title: "روز شروع",
                                    width: 20
                                },{
                                    field: "FromMonth",
                                    title: "ماه شروع",
                                    width: 20
                                },{
                                    field: "ToDay",
                                    title: "روز پایان",
                                    width: 20
                                },{
                                    field: "ToMonth",
                                    title: "ماه پایان",
                                    width: 20
                                },{
                                    command: [{
                                        name: "edit",
                                        text: { edit: "@T("Admin.Common.Edit")", update: "ثبت", cancel: "انصراف" }
                                    }],
                                    width: 100
                                }]
                            });
                        });
                    </script>

                    <script type="text/javascript">

                        $(document).ready(function () {
                            $("#CTariffId").change(function () {
                                //search
                                var grid = $('#tariffs-grid').data('kendoGrid');
                                grid.dataSource.read();
                                return false;
                            });
                        });

                        function additionalData() {
                            return {
                                CTariffId: $('#CTariffId').val()
                            };
                        }
                    </script>
                </td>
            </tr>
        </table>
    </div>
}

<script type="text/javascript">
    $(document).ready(function(){
        $("#tariff-tab").css('background', '#2f363a');
    });
</script>

Presentation/Energy.Web/Views/Tariff/TariffList.cshtml
@model TariffListModel
@using System.Globalization;
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Energy.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Energy.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = "لیست تعرفه ها";
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            @*<img src="@Url.Content("~/Content/images/ico-tariffs.png")" alt="" />*@
            <span class="page-title">لیست تعرفه ها</span>
        </div>
    </div>
    <div class="fieldset product-selectors">
        <table width="100%">
            <tr>
                <td class="adminTitle" style="width:10%">
                    @Html.LabelFor(model => model.CTariffId):
                </td>
                <td class="adminData">
                    @Html.DropDownList("CTariffId", Model.CTariffs)
                </td>
            </tr>
        </table>
    </div>
    <hr />

    <div class="fieldset">
        <table class="adminContent" style="width:100%;">
            <tr>
                <td>
                    <div class="k-rtl" id="tariffs-grid" style="width:100%;"></div>

                    <script>
                        $(document).ready(function () {
                            $("#tariffs-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("TariffList", "Tariff"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: additionalData
                                        },
                                        update: {
                                            url:"@Html.Raw(Url.Action("TariffUpdate", "Tariff"))",
                                            type: "POST",
                                            dataType: "json",
                                        },
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "Id", // define the model of the data source. Required for validation and property types.
                                            fields: {
                                                "Id":{ editable: false },
                                                "CTariff": { editable: false }, //تعيين نوع فيلد براي جستجوي پويا مهم است
                                                "Title": { type: "string", editable: false },
                                                "LimitCostKwh": { editable: true },
                                                "MaxFine": { editable: true },
                                                "MinDiscount": { editable: true },
                                                "NoMaxDiscount": { editable: true },
                                                "Factor": { editable: true },
                                                "PowerCost": { editable: true },
                                                "MidCost": { editable: true },
                                                "MaxCost":{ editable: true },
                                                "MinCost":{ editable: true, decimals: 10, format:"{n6}" },
                                            }
                                        }
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(defaultGridPageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: false
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(gridPageSizes)]
                                },
                                sortable: true,
                                scrollable: false,
                                editable: {
                                    mode: "popup"
                                },
                                columns: [ {
                                    field: "CTariff",
                                    title: "تعرفه",
                                    width: 50
                                },{
                                    field: "Title",
                                    title: "عنوان",
                                    width: 80
                                },{
                                    field: "Description",
                                    title: "توضیحات",
                                    width: 150
                                },{
                                    field: "LimitCostKwh",
                                    title: "حداکثر بها ",
                                    width: 100,
                                },{
                                    field: "MinDiscount",
                                    title: "تخفیف کم باری",
                                    width: 100,
                                },{
                                    field: "NoMaxDiscount",
                                    title: "تخفیف غیراوج بار",
                                    width: 20,
                                },{
                                    field: "Factor",
                                    title: "ضریب",
                                    width: 20
                                },{
                                    field: "PowerCost",
                                    title: "بهای قدرت",
                                    width: 20,
                                },{
                                    field: "MidCost",
                                    title: "میان بار",
                                    width: 20,
                                },{
                                    field: "MaxCost",
                                    title: "اوج بار",
                                    width: 20,
                                },{
                                    field: "MinCost",
                                    title: "کم باری",
                                    width: 20,
                                },{
                                    command: [{
                                        name: "edit",
                                        text: { edit: "@T("Admin.Common.Edit")", update: "ثبت", cancel: "انصراف" }
                                    }],
                                    width: 100
                                }]
                            });
                        });
                    </script>

                    <script type="text/javascript">

                        $(document).ready(function () {
                            $("#CTariffId").change(function () {
                                //search
                                var grid = $('#tariffs-grid').data('kendoGrid');
                                grid.dataSource.read();
                                return false;
                            });
                        });

                        function additionalData() {
                            return {
                                CTariffId: $('#CTariffId').val()
                            };
                        }
                    </script>
                </td>
            </tr>
        </table>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#tariff-tab").css('background', '#2f363a');
    });
</script>