Presentation/Energy.Web/Models/Bills/BillModel.cs
using System;
using System.Collections.Generic;
using Energy.Core.Domain.Bills;
using Energy.Core.Domain.Customers;
using Energy.Core.Domain.Splits;
using Energy.Web.Framework.Mvc;
using Energy.Core.Domain.Constant;
using Energy.Core.Domain.Tariffs;
using System.ComponentModel.DataAnnotations;
using Energy.Web.Framework;

namespace Energy.Web.Models.Bills
{
    public class BillModel : BaseProEntityModel
    {
        public virtual Split Split { get; set; }
        public virtual Int32 SplitID { get; set; }
        public virtual Int32 Term { get; set; }
        public virtual Int32 Year { get; set; }
        public virtual DateTime DateReadPre { get; set; }
        public virtual string DateReadPrePersian { get; set; }
        public virtual Double MidReadPre { get; set; }
        public virtual Double MaxReadPre { get; set; }
        public virtual Double MinReadPre { get; set; }
        public virtual Double ReactReadPre { get; set; }
        public virtual Double PowerReadPre { get; set; }

        public virtual Int32 TariffID { get; set; }
        public virtual Int32 TariffAreaID { get; set; }

        [UIHint("PersianDateNullable")]
        public virtual DateTime DateRead { get; set; }

        public virtual string DateReadPersian { get; set; }
        public virtual Double MidRead { get; set; }
        public virtual Double MaxRead { get; set; }
        public virtual Double MinRead { get; set; }
        public virtual Double ReactRead { get; set; }
        public virtual Double PowerRead { get; set; }
        public virtual Double FridayRead { get; set; }

        public virtual Double AllDays { get; set; }
        public virtual Double MidUsed { get; set; }
        public virtual Double MaxUsed { get; set; }
        public virtual Double MinUsed { get; set; }
        public virtual Double ReactUsed { get; set; }
        public virtual Double FridayUsed { get; set; }
        public virtual Double AllUsed { get; set; }
        public virtual Double PowerUsed { get; set; }

        public virtual Int64 Total { get; set; }
        public virtual Int64 Discount { get; set; }
        public virtual Int64 Tax { get; set; }
        public virtual Int64 Toll { get; set; }
        public virtual Int64 Round { get; set; }
        public virtual Int64 Payable { get; set; }
        public virtual DateTime? issueDate { get; set; }
        public virtual DateTime? ExpDate { get; set; }
        public virtual Int64 Paid { get; set; }
        public virtual Int64 Debit { get; set; }
        public virtual DateTime? PaidDate { get; set; }

        public virtual String PaymentID { get; set; }

        public virtual String PaymentIdWD { get; set; }

        public virtual DateTime? EditDate { get; set; }
        public virtual Boolean Fixed { get; set; }

        public virtual Double NormalDays { get; set; }
        public virtual Double WarmDays { get; set; }
        public virtual Double WarmDaysFactor { get; set; }
        public virtual Double WarmDaysX { get; set; }
        public virtual Double AllDaysX { get; set; }
        public virtual Double NormalUsed { get; set; }
        public virtual Double WarmUsed { get; set; }
        public virtual Double NormalUsedAvrg { get; set; }
        public virtual Double WarmUsedAvrg { get; set; }
        public virtual Double NormalCostAvrg { get; set; }
        public virtual Double WarmCostAvrg { get; set; }
        public virtual Double NormalCost { get; set; }
        public virtual Double WarmCost { get; set; }
        public virtual Int64 AllCost { get; set; }

        public virtual Double WarmMaxUsed { get; set; }
        public virtual Double WarmMaxFineCost { get; set; }

        public virtual Double NormalMaxUsed { get; set; }
        public virtual Double NormalMaxFineCost { get; set; }

        public virtual Int64 FineCost { get; set; }

        public virtual Double WarmMindUsed { get; set; }
        public virtual Double WarmMindDiscountCost { get; set; }

        public virtual Double NormalMindUsed { get; set; }
        public virtual Double NormalMindDiscountCost { get; set; }

        public virtual Int64 DiscountCost { get; set; }

        public virtual Double MidRate { get; set; }
        public virtual Double MaxRate { get; set; }
        public virtual Double MinRate { get; set; }
        public virtual Double ReactRate { get; set; }
        public virtual Double MidCost { get; set; }
        public virtual Double MaxCost { get; set; }
        public virtual Double MinCost { get; set; }
        public virtual Double ReactCost { get; set; }
        public virtual Double PowerCost { get; set; }
        public virtual Double Power90 { get; set; }
        public virtual Int64 Power90Cost { get; set; }
        public virtual Int64 IndustDisCost { get; set; }
        public virtual Int64 FreelanceCost { get; set; }
        public virtual Int64 ExceedCost { get; set; }
        public virtual Int64 NetworkCost { get; set; }
        public virtual Int64 UnIndustCost { get; set; }
        public virtual Int64 TagExpireCost { get; set; }
        public virtual Double PowerFactor { get; set; }
        public virtual Double LossFactor { get; set; }
        public virtual String Title { get; set; }
        public virtual String Description { get; set; }
        public virtual String Emergency { get; set; }
        public virtual string Type { get; set; }
        public virtual bool exist { get; set; }
        public virtual int rowNumber { get; set; }
        public virtual bool selected { get; set; }
        public virtual IList<BillNormal> billNormal { get; set; }
        public virtual IList<TariffRate> tariffRates { get; set; }
        public virtual double LatePenalty { get; set; }
        public virtual int PictureId { get; set; }
        public virtual string PictureUrl { get; set; }

        #region Nested classes

        public partial class BillPictureModel : BaseProEntityModel
        {
            public int BillId { get; set; }

            [UIHint("Picture")]
            [ProResourceDisplayName("Admin.Documents.Files.Fields.FileName")]
            public int PicId { get; set; }

            [ProResourceDisplayName("Admin.Documents.Files.Fields.Description")]
            public string Description { get; set; }
        }

        #endregion
    }

    
}

Presentation/Energy.Web/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Energy.Core;
using Energy.Core.Domain.Customers;
using Energy.Core.Domain.Constant;
using Energy.Services.Common;
using Energy.Services.Bills;
using Energy.Services.Security;
using Energy.Services.Splits;
using Energy.Services.Tariffs;
using Energy.Services.Logging;
using Energy.Web.Models.Splits;
using Energy.Web.Models.Bills;
using Energy.Web.Framework.Kendoui;
using Energy.Web.Extensions;
using System.Text;
using Web.Tools;
using Energy.Web.Framework.Mvc;
using System.IO;
using System.Converter;
using Energy.Core.Domain.Bills;

namespace Energy.Web.Controllers
{
    public class BillController : BaseAdminController
    {
        #region Fields

        private readonly ISplitService _splitService;
        private readonly IBillService _billService;
        private readonly IBillNormalService _billNormalService;
        private readonly ITariffService _tariffService;
        private readonly IPermissionService _permissionService;
        private readonly IWorkContext _workContext;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPdfService _pdfService;

        #endregion

        #region Ctor
        public BillController(
            ISplitService splitService,
            IBillService billService,
            ITariffService tariffService,
            IBillNormalService billNormalService,
            IPermissionService permissionService,
            IWorkContext workContext,
            ICustomerActivityService customerActivityService,
            IPdfService pdfService)
        {
            this._splitService = splitService;
            this._billService = billService;
            this._tariffService = tariffService;
            this._billNormalService = billNormalService;
            this._permissionService = permissionService;
            this._workContext = workContext;
            this._customerActivityService = customerActivityService;
            this._pdfService = pdfService;
        }

        #endregion

        #region Methods
        public ActionResult Index()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBills))
                return AccessDeniedView();

            var model = new SplitListModel();
            return View("Bills", model);
        }

        public ActionResult UploadFile(int id)
        {
            var model = new BillModel.BillPictureModel();
            model.BillId = id;
            var bill = _billService.getById(id);
            if (bill != null)
                model.PicId = bill.PictureId;
            return View(model);
        }

        public ActionResult SavePicture(BillModel.BillPictureModel model)
        {
            var bill = _billService.getById(model.BillId);
            if (bill == null)
                return null;

            bill.PictureId = model.PicId;
            _billService.UpdateBill(bill);

            //activity log
            _customerActivityService.InsertActivity("Bills.AttachFile", model.Description);
            return Json(null);
        }

        public ActionResult CalculateBill(int id)
        {
            StringBuilder content = new StringBuilder();

            var bill = _billService.getById(id);

            var result = Calculate.CalculateBill(_billService, _splitService, _tariffService, _billNormalService, bill.Id);

            if (result == 1)
                content.AppendLine("محاسبه صورتحساب انشعاب  " + bill.SplitID + " مربوط به سال " + bill.Year + " دوره " + bill.Term + " با موفقیت انجام شد ");
            else if (result == 2)
                content.AppendLine("محاسبه صورتحساب به دلیل غیرفعال بودن انشعاب مربوطه، انجام نشد");
            else if (result == 0)
                content.AppendLine("محاسبه صورتحساب با مشکل مواجه شد. لطفا با پشتیبانی سیستم تماس بگیرید");

            return Json(new { msg = content.ToString() });
        }

        public ActionResult CalculateAllBills()
        {
            StringBuilder content = new StringBuilder();

            var bills = _billService.GetBills();

            var lastYear = (from b in bills
                            select b.Year).Max();

            var lastTerm = (from b in bills
                            where b.Year == lastYear
                            select b.Term).Max();

            var lastTermBills = _billService.GetBillsByDate(lastYear, lastTerm);

            foreach (var bill in lastTermBills)
            {
                Calculate.CalculateBill(_billService, _splitService, _tariffService, _billNormalService, bill.Id);
            }

            content.AppendLine("محاسبه صورتحساب های مربوط به سال " + lastYear.ToString() + " دوره " + lastTerm.ToString() + " با موفقیت انجام شد ");

            return Json(new { msg = content.ToString() });
        }

        public ActionResult BillDetail(int id)
        {
            var bill = _billService.getBillaSpiltById(id);

            var model = bill.ToModel();

            if (model.Split.Demand == (int)CDemand.Normal)
            {
                model.billNormal = _billNormalService.GetByBillId(bill.Id);
                model.tariffRates = _billNormalService.GetTariffRates(bill.TariffID);
                return View("BillDetail_N", model);
            }
            else
                return View("BillDetail_D", model);

        }

        public ActionResult PdfBill(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBills))
                return AccessDeniedView();

            //load bills
            var bill = _billService.getById(id);

            byte[] bytes;
            using (var stream = new MemoryStream())
            {
                _pdfService.PrintBillToPdf(stream, bill, true);
                bytes = stream.ToArray();
            }
            return File(bytes, "application/pdf", string.Format("bill_{0}{1}_{2}.pdf", bill.Year, bill.Term, bill.Id));
        }

        public ActionResult PdfBillAll()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBills))
                return AccessDeniedView();

            //load bills
            var bills = _billService.GetBills();

            var lastYear = (from b in bills
                            select b.Year).Max();

            var lastTerm = (from b in bills
                            where b.Year == lastYear
                            select b.Term).Max();

            var lastTermBills = _billService.GetBillsByDate(lastYear, lastTerm);

            byte[] bytes;
            using (var stream = new MemoryStream())
            {
                _pdfService.PrintBillsToPdf(stream, lastTermBills, true);
                bytes = stream.ToArray();
            }
            return File(bytes, "application/pdf", string.Format("bills_{0}-{1}.pdf", lastYear, lastTerm));
        }

        public ActionResult GetDebitlessPaymentId(string splitId, string payable)
        {
            var paymentId = Calculate.IDGenerator(
                Convert.ToInt64(splitId), Convert.ToInt64(payable));

            return Content(paymentId.ToString());
        }

        #endregion

        #region Kendo Methods

        [HttpPost]
        public ActionResult List(DataSourceRequest command, int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBills))
                return AccessDeniedView();

            var bills = _billService.GetAllBills(
                splitId: id,
                year: 0,
                month: 0,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize);

            if (command.Page == 1 && bills.Count > 0)
                bills[0].IsLastTerm = true;

            foreach (var bill in bills)
            {
                switch (bill.Type)
                {
                    case "main":
                        bill.Type = "اصلی";
                        break;
                    case "archive":
                        bill.Type = "بایگانی";
                        break;
                    case "corrective":
                        bill.Type = "اصلاحی";
                        break;
                    case "midterm":
                        bill.Type = "میان دوره";
                        break;
                    case "zero":
                        bill.Type = "کنتور صفر";
                        break;
                }
            }

            var gridModel = new DataSourceResult
            {
                Data = bills,
                Total = bills.TotalCount,
            };

            return Json(gridModel, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Update(BillModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBills))
                return AccessDeniedView();

            var bill = _billService.getById(model.Id);

            bill.DateRead = model.DateRead;
            bill.MinRead = model.MinRead;
            bill.MaxRead = model.MaxRead;
            bill.MidRead = model.MidRead;
            bill.ReactRead = model.ReactRead;
            bill.PowerRead = model.PowerRead;
            bill.Debit = model.Debit;

            _billService.UpdateBill(bill);

            return new NullJsonResult();
        }

        [HttpPost]
        public ActionResult Create(BillModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBills))
                return AccessDeniedView();


           var newBill = new Bill
           {
               SplitID = Convert.ToInt32(model.SplitID),
               // skip 7, 1
               DateRead = DateHelper.PersianToDateTime(model.DateReadPersian),
               // skip 7, 2
               MidRead = Convert.ToDouble(model.MidRead),

Presentation/Energy.Web/Views/Bill/Bills.cshtml
@model SplitListModel
@using System.Globalization;
@{
    var defaultGridPageSize = 10;
    var gridPageSizes = 10;

    //page title
    ViewBag.Title = "مشاهده صورتحساب";
}

@helper TabBillsInfo()
{
    @Html.Partial("_Bills.Info", Model)
}

<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Content/images/ico-customers.png")" alt="" />
        <span class="page-title">مشاهده صورتحساب</span>
    </div>
    <div class="options">
        <input type="button" id="calculate-btn" name="calculate" class="k-button" value="محاسبه صورتحساب های آخرین دوره" />
        <input type="button" id="pdf-bill-all" class="k-button" value="ذخیره صورتحساب های آخرین دوره با فرمت pdf" />
    </div>
</div>
<div id="cal-dialog" title="محاسبه صورتحسابهای دوره جدید" style="padding-left:35px;padding-top:15px;">
    <p>در صورت تایید، تمامی صورتحساب های آخرین دوره محاسبه میشوند</p>
</div>
<script>
    $("#calculate-btn").click(function () {
        $("#cal-dialog").dialog("open");
    });

    $('#cal-dialog').dialog({
        autoOpen: false,
        modal: true,
        show: {
            effect: "Highlight",
            duration: 4000
        },
        hide: {
            effect: "Highlight",
            duration: 4000
        },
        buttons: {
            'تایید': function () {
                var loading = $("<i class='loading'></div>");
                var p = $('#cal-dialog p');
                p.html("");
                p.append(loading);
                working = true;
                var $this = $(this);
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("/CalculateAllBills")',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                        working = false;
                        loading.remove();
                        var p = $('#cal-dialog p');
                        p.html(result.msg);
                        $('span:contains("تایید")').parent().css('display', 'none');
                        $('span:contains("انصراف")').html('بستن');
                    },
                    error: function (objAjaxRequest, strError) {
                        var respText = objAjaxRequest.responseText;
                        console.log(respText);
                        //working = false;
                        //loading.remove();
                        //$('#create_result').html(respText);
                        $(self).dialog("close");
                    }
                });
            },
            'انصراف': function () {
                $(this).dialog('close');
            }
        }
    });

    $('#pdf-bill-all').click(function (e) {
        e.preventDefault();
        $('#export-pdf-selected-form').submit();
        return false;
    });

</script>

@using (Html.BeginForm("PdfBillAll", "Bill", FormMethod.Post, new { id = "export-pdf-selected-form" }))
{
    
}

<div class="news-list-homepage">
    <div style="padding:2px;" class="col-md-9 col-sm-9 col-xs-12">
        <table class="adminContent" style="width:100%;">
            <tr>
                <td>
                    <div id="splits-grid" style="width:100%;"></div>
                    <script>
                        $(function () {
                            $("#bill-tab").css('background', '#2f363a')
                        })

                        $(document).ready(function () {
                            $("#splits-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("SplitList", "Split"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: additionalData
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "Id",
                                            title: "Title",}
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(defaultGridPageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(gridPageSizes)]
                                },
                                scrollable: false,
                                dataBound: onDataBound,
                                columns: [ {
                                    field: "Id",
                                    title: "انشعاب",
                                    width: 50
                                }, {
                                    field: "Title",
                                    title: "عنوان"
                                }, {
                                    field: "CustomerName",
                                    title: "مشترک",
                                    width: 100,
                                },
                                {
                                    field: "Tariff",
                                    title: "تعرفه",
                                    width: 100
                                },{
                                    field: "SerialNo",
                                    title: "شماره سریال",
                                    width: 100
                                },
                                {
                                    field: "Active",
                                    title: "فعال",
                                    width: 100,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '<img src="@Url.Content("~/Content/images/")active-#=Active#.gif" />'
                                },  {
                                    field: "Id",
                                    title: "صورتحساب",
                                    width: 50,
                                    template: '<a onClick="LoadBills(#=Id#)">مشاهده</a>'
                                }]
                            });
                        });
                    </script>

                    <script type="text/javascript">
                        $(document).ready(function () {

                            //search button
                            $('#search-splits').click(function () {
                                var grid = $('#splits-grid').data('kendoGrid');
                                grid.dataSource.page(1); //new search. Set page size to 1
                                return false;
                            });

                            $("#@Html.FieldIdFor(model => model.splitId)").keydown(function (event) {
                                if (event.keyCode == 13) {
                                    $("#search-splits").click();
                                    return false;
                                }
                            });
                            $("#@Html.FieldIdFor(model => model.customerName)").keydown(function (event) {
                                if (event.keyCode == 13) {
                                    $("#search-splits").click();
                                    return false;
                                }
                            });
                            $("#@Html.FieldIdFor(model => model.splitName)").keydown(function (event) {
                                if (event.keyCode == 13) {
                                    $("#search-splits").click();
                                    return false;
                                }
                            });
                            $("#@Html.FieldIdFor(model => model.fileNo)").keydown(function (event) {
                                if (event.keyCode == 13) {
                                    $("#search-splits").click();
                                    return false;
                                }
                            });
                            $("#@Html.FieldIdFor(model => model.serialNo)").keydown(function (event) {
                                if (event.keyCode == 13) {
                                    $("#search-splits").click();
                                    return false;
                                }
                            });
                        });

                        function onDataBound(e) {
                        }

                        function additionalData() {
                            return {
                                splitId: $('#@Html.FieldIdFor(model => model.splitId)').val(),
                                customerName: $('#@Html.FieldIdFor(model => model.customerName)').val(),
                                splitName: $('#@Html.FieldIdFor(model => model.splitName)').val(),
                                fileNo: $('#@Html.FieldIdFor(model => model.fileNo)').val(),
                                serialNo: $('#@Html.FieldIdFor(model => model.serialNo)').val(),
                            };
                        }
                    </script>
                </td>
            </tr>
        </table>
    </div>
    <div class="news-items">
        <div style="padding:2px;" class="col-md-3 col-sm-3 col-xs-12">
            <div class="k-header search-title">
                <span>مشخصات انشعاب</span>
            </div>
            <div class="item">
                <table>
                    <tr style="margin-bottom:10px;">
                        <td>
                            <div class="inputs">
                                <label for="splitId">شماره انشعاب :</label>
                                @Html.EditorFor(model => model.splitId)
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="inputs">
                                <label for="customerName">نام مشترک :</label>
                                @Html.EditorFor(model => model.customerName)
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="inputs">
                                <label for="splitName">نام انشعاب :</label>
                                @Html.EditorFor(model => model.splitName)
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="inputs">
                                <label for="fileNo">شماره پرونده :</label>
                                @Html.EditorFor(model => model.fileNo)
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="inputs">
                                <label for="serialNo">شماره سریال کنتور</label>
                                @Html.EditorFor(model => model.serialNo)
                            </div>
                        </td>
                    </tr>
                </table>
                <input type="button" id="search-splits" class="k-button" value="@T("جستجو")" />
            </div>
        </div>
    </div>
</div>
<div>
    <h1 id="bills-title" style="font-size:22px"></h1>
</div>
<hr />

<div>
    @TabBillsInfo()
</div>

Presentation/Energy.Web/Views/Bill/UploadFile.cshtml
@model BillModel.BillPictureModel
@using System.Globalization;

@{
    ViewBag.Title = "اپلود فایل صورتحساب";
    Layout = "~/Views/Shared/_Root.Head.cshtml";
}


@using (Html.BeginForm("SavePicture", "Bill"))
{
    @Html.HiddenFor(model => model.BillId)
    <div class="container" style="padding-top:20px;">
        <div class="page split-page">
            <div class="page-body">
                <div class="fieldset">
                    <div class="title" style="width:100%">
                        <strong>اپلود فایل صورتحساب</strong>
                        <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" style="float:left;width:100px" />
                    </div>

                    <hr />
                    <div class="form-fields">
                        <div class="inputs">
                            @Html.LabelFor(Model => Model.Description, new { style = "vertical-align:top" })
                            @Html.TextAreaFor(Model => Model.Description)
                        </div>
                    </div>
                    <div class="form-fields">
                        <div class="inputs">
                            @Html.EditorFor(Model => Model.PicId)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}